[myhosts]
192.168.191.139 ansible_user=jerryale40 ansible_ssh_pass=Winner33!
192.168.191.140 ansible_user=jerryale40 ansible_ssh_pass=Winner33!
192.168.191.132 ansible_user=jerryale40 ansible_ssh_pass=Winner33!
192.168.191.141 ansible_user=jerryale40 ansible_ssh_pass=Winner33!
